# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 16:45
from __future__ import unicode_literals

from django.db import migrations

from restapi.permissions import PLAN_MANAGER, USER_MANAGER

def run(apps=None, schema_editor=None):
    # get models
    Group = apps.get_model("auth", "group")
    Permission = apps.get_model("auth", "permission")

    plan_manager = Group.objects.get_or_create(name=PLAN_MANAGER)
    user_manager = Group.objects.get_or_create(name=USER_MANAGER)


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(run),
    ]
